/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.qnoid.helloworld

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class HelloTest {
    @Test fun testSuccess() {
        assertTrue(true)
    }
}
